[build-system]
requires = ["sip >=5", "PyQt-builder", "PyQt5"]
build-backend = "sipbuild.api"

[tool.sip.metadata]
name = "SciDAVis"
version = "2.4.0"

[tools.sip]
abi-version = "12.9"
project-factory = "pyqtbuild:PyQtProject"

[tool.sip.project]
sip-files-dir = "."
